namespace: fleet-mc-helm-example
targetCustomizations:
- name: dev
  helm:
    values:
      replicas: 1
  clusterSelector:
    matchLabels:
      stage: dev

- name: test
  helm:
    values:
      replicas: 5
  clusterSelector:
    matchLabels:
      stage: test

- name: prod
  helm:
    values:
      serviceType: NodePort
      replicas: 10
  clusterSelector:
    matchLabels:
      stage: prod
